#!/bin/sh
# Xcode Cloud post-clone hook.
#
# Two files the build needs are gitignored, so a clean checkout lacks them and
# the build fails. Generate both here:
#
#   1. Secrets.swift        — runtime Sentry DSN (from the SENTRY_DSN env var).
#   2. Sentry.xcconfig      — referenced as a base configuration in the project,
#                             so it MUST exist or the build can't open it. Holds
#                             the dSYM-upload auth token; empty is fine on CI.
#
# Neither secret is required for the build to succeed. Without SENTRY_DSN the
# app builds and simply skips Sentry init. Without a token the dSYM-upload build
# phase self-skips (it also needs sentry-cli, which isn't installed on Cloud).
set -e

REPO="$CI_PRIMARY_REPOSITORY_PATH"

# 1. Secrets.swift (runtime DSN)
cat > "$REPO/TrimrPix for iOS/Secrets.swift" <<SWIFT
// Generated by ci_scripts/ci_post_clone.sh (Xcode Cloud) — do not edit.
enum Secrets {
    static let sentryDSN = "${SENTRY_DSN:-YOUR_SENTRY_DSN_HERE}"
}
SWIFT

# 2. Sentry.xcconfig (base configuration reference — must exist)
cat > "$REPO/Sentry.xcconfig" <<XCCONFIG
// Generated by ci_scripts/ci_post_clone.sh (Xcode Cloud) — do not edit.
SENTRY_AUTH_TOKEN = ${SENTRY_AUTH_TOKEN:-}
XCCONFIG

echo "Wrote Secrets.swift ($([ -n "$SENTRY_DSN" ] && echo 'DSN present' || echo 'no DSN, Sentry disabled'))"
echo "Wrote Sentry.xcconfig ($([ -n "$SENTRY_AUTH_TOKEN" ] && echo 'token present' || echo 'no token, dSYM upload skipped'))"
