#!/bin/sh
# Xcode Cloud post-clone hook.
#
# Secrets.swift is gitignored, so Xcode Cloud's clean checkout doesn't have it
# and the build would fail. Generate it here from the SENTRY_DSN environment
# variable (set it on the Xcode Cloud workflow). Without the variable the app
# still builds and runs fine; it just skips Sentry initialization (the app
# guards on the placeholder value).
#
# The Sentry dSYM-upload build phase self-skips on Xcode Cloud (no sentry-cli,
# no SENTRY_AUTH_TOKEN) with a warning — that is expected and harmless.
set -e

SECRETS_FILE="$CI_PRIMARY_REPOSITORY_PATH/TrimrPix for iOS/Secrets.swift"

cat > "$SECRETS_FILE" <<SWIFT
// Generated by ci_scripts/ci_post_clone.sh (Xcode Cloud) — do not edit.
enum Secrets {
    static let sentryDSN = "${SENTRY_DSN:-YOUR_SENTRY_DSN_HERE}"
}
SWIFT

if [ -n "$SENTRY_DSN" ]; then
    echo "Wrote Secrets.swift (Sentry DSN present)"
else
    echo "Wrote Secrets.swift (SENTRY_DSN not set — Sentry will be disabled in this build)"
fi
